name: python_workshop_project
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - markdown-it-py=4.0.0=py313haa95532_1
  - mdurl=0.1.2=py313haa95532_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - pygments=2.19.2=py313haa95532_0
  - python=3.13.11=h260b955_100_cp313
  - python_abi=3.13=3_cp313
  - rich=14.2.0=py313haa95532_0
  - setuptools=80.9.0=py313haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - idna==3.11
      - openfoodfacts==3.3.0
      - prompt-toolkit==3.0.52
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - questionary==2.1.1
      - requests==2.32.5
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - wcwidth==0.2.14
prefix: C:\Users\Asus\anaconda3\envs\python_workshop_project
